name: Playwright Testing Demo

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test: 
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up a Node.js project
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies from package.json
      - name: Install dependencies from package.json
        run: npm install

      # Download Playwright browsers
      - name: Download Playwright browsers
        run: npx playwright install --with-deps

      # Run Playwright tests
      - name: Run tests
        run: npx playwright test
